/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50612
Source Host           : localhost:3306
Source Database       : scriptdev22

Target Server Type    : MYSQL
Target Server Version : 50612
File Encoding         : 65001

Date: 2013-09-22 11:03:42
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `wuzhu_texts`
-- ----------------------------
DROP TABLE IF EXISTS `wuzhu_texts`;
CREATE TABLE `wuzhu_texts` (
  `entry` mediumint(8) NOT NULL DEFAULT '-60003',
  `content_default` text NOT NULL,
  `content_loc1` text,
  `content_loc2` text,
  `content_loc3` text,
  `content_loc4` text,
  `content_loc5` text,
  `content_loc6` text,
  `content_loc7` text,
  `content_loc8` text,
  `comment` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Custom Texts';

-- ----------------------------
-- Records of wuzhu_texts
-- ----------------------------
INSERT INTO `wuzhu_texts` VALUES ('-6000000', 'wuzhu魔兽自定义字符串开始', null, null, null, 'wuzhu魔兽自定义字符串开始', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000001', '使用此功能将消费G', null, null, null, '使用此功能将消费G', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000002', '|cffff0000你的金钱不足.|r', null, null, null, '|cffff0000你的金钱不足.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000004', '|cffff0000无法在战斗中访问，请停止战斗再访问.|r', null, null, null, '|cffff0000无法在战斗中访问，请停止战斗再访问.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000005', '【在线积分】[降级服务] ', null, null, null, '【在线积分】[降级服务] ', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000006', '【在线积分】[积分升级]', null, null, null, '【在线积分】[积分升级]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000007', '【在线积分】[物品兑换积分]', null, null, null, '【在线积分】[物品兑换积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000008', '【在线积分】[积分购买荣誉点数]', null, null, null, '【在线积分】[积分购买荣誉点数]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000009', '【在线积分】[积分购买技能点数]', null, null, null, '【在线积分】[积分购买技能点数]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000010', '【在线积分】[购买积分]', null, null, null, '【在线积分】[购买积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000011', '【在线积分】[查询积分]', null, null, null, '【在线积分】[查询积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000012', '【降级服务】[角色等级下降十级]', null, null, null, '【降级服务】[角色等级下降十级]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000013', '【降级服务】[|cffff0000角色等级降为一级|r]', null, null, null, '【降级服务】[|cffff0000角色等级降为一级|r]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000014', '|cffff0000你的等级已经最低|r', null, null, null, '|cffff0000你的等级已经最低|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000015', '|cff8000ff<<<返回首页>>>|r', null, null, null, '|cff8000ff<<<返回首页>>>|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000016', '【兑换积分】[十英雄纹章换一万积分] ', null, null, null, '【兑换积分】[一英雄纹章换一千积分] ', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000017', '【兑换积分】[十勇气纹章换二万积分]', null, null, null, '【兑换积分】[十英雄纹章换一万积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000018', '【兑换积分】[百英雄纹章换十万积分]', null, null, null, '【兑换积分】[百英雄纹章换十万积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000019', '【兑换积分】[百勇气纹章换二十万积分]', null, null, null, '【兑换积分】[一积分币换二千积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000020', '【兑换积分】[十积分币换二万积分]', null, null, null, '【兑换积分】[十积分币换二万积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000021', '【兑换积分】[百积分币换二十万积分]', null, null, null, '【兑换积分】[五十积分币换十万积分]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000022', '【消费】[一千积分购买二百荣誉点数]', null, null, null, '【消费】[一千积分购买二百荣誉点数]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000023', '【消费】[一万积分购买二千荣誉点数]', null, null, null, '【消费】[一万积分购买二千荣誉点数]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000024', '【消费】[十万积分购买二万荣誉点数]', null, null, null, '【消费】[十万积分购买二万荣誉点数]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000025', '【消费】[百万积分购买二十万荣誉点数]', null, null, null, '【消费】[百万积分购买二十万荣誉点数]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000027', '【消费】[一万积分加采矿技能五十点]', null, null, null, '【消费】[一万积分加采矿技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000028', '【消费】[一万积分加炼金技能五十点]', null, null, null, '【消费】[一万积分加炼金技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000029', '【消费】[一万积分加锻造技能五十点]', null, null, null, '【消费】[一万积分加锻造技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000030', '【消费】[一万积分加裁缝技能五十点]', null, null, null, '【消费】[一万积分加裁缝技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000031', '【消费】[一万积分加烹饪技能五十点]', null, null, null, '【消费】[一万积分加烹饪技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000032', '【消费】[一万积分加制皮技能五十点]', null, null, null, '【消费】[一万积分加制皮技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000033', '【消费】[一万积分加钓鱼技能五十点]', null, null, null, '【消费】[一万积分加钓鱼技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000034', '【消费】[一万积分加附魔技能五十点]', null, null, null, '【消费】[一万积分加附魔技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000035', '【消费】[一万积分加珠宝技能五十点]', null, null, null, '【消费】[一万积分加珠宝技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000036', '【消费】[一万积分加工程技能五十点]', null, null, null, '【消费】[一万积分加工程技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000037', '【消费】[一万积分加急救技能五十点]', null, null, null, '【消费】[一万积分加急救技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000038', '【消费】[一万积分加草药技能五十点]', null, null, null, '【消费】[一万积分加草药技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000039', '【消费】[一万积分加剥皮技能五十点]', null, null, null, '【消费】[一万积分加剥皮技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000040', '【消费】[一万积分加开锁技能五十点]', null, null, null, '【消费】[一万积分加开锁技能五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000041', '【消费】[一万积分加防御武器五十点]', null, null, null, '【消费】[一万积分加防御武器五十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000042', '|cffff0000你的等级已经最高|r', null, null, null, '|cffff0000你的等级已经最高|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000043', '|cff8000ff【升一级】[需要积分：', null, null, null, '|cff8000ff【升一级】[需要积分：', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000044', ']|r', null, null, null, ']|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000045', '|cffaa0080你当前共有积分：%u.|r ', null, null, null, '|cffaa0080你当前共有积分：%u.|r ', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000046', '|cffff0000你缺少换积分的物品.|r', null, null, null, '|cffff0000你缺少换积分的物品.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000047', '|cff8000ff你增加积分：%u.|r', null, null, null, '|cff8000ff你增加积分：%u.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000048', '|cffff0000你的积分不够.|r', null, null, null, '|cffff0000你的积分不够.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000049', ' |cffaa0080你荣誉点数增加：%u，当前荣誉点数：%u.|r', null, null, null, ' |cffaa0080你荣誉点数增加：%u，当前荣誉点数：%u.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000050', '|cffaa0080技能点数增加，你当前还有积分：%u.|r', null, null, null, '|cffaa0080技能点数增加，你当前还有积分：%u.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000051', '|cffff0000技能点数增加失败，可能你未学此技能或技能已经到最大值.|r', null, null, null, '|cffff0000技能点数增加失败，可能你未学此技能或技能已经到最大值.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000052', '|cffaa0080等级提高一级，你当前还有积分：%u.|r', null, null, null, '|cffaa0080等级提高一级，你当前还有积分：%u.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000053', ' |cffaa0080您当前等级为：%u.|r', null, null, null, ' |cffaa0080您当前等级为：%u.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000054', '|cffaa0080你可以通过现金购买积分，详情请联系QQ:85267512.|r', null, null, null, '|cffaa0080你可以通过现金购买积分，详情请联系QQ:85267512.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000055', '|cffff0000无法在战斗中使用宝石.|r', null, null, null, '|cffff0000无法在战斗中使用宝石.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000056', '|cffff0000无法在坐骑中使用宝石.|r', null, null, null, '|cffff0000无法在坐骑中使用宝石.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000057', '|cff6000ff【城市】[主要城市传送]|r', null, null, null, '|cff6000ff【城市】[主要城市传送]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000058', '|cff7000ff【商店】[积分购物商城]|r', null, null, null, '|cff7000ff【商店】[积分购物商城]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000059', '|cff8000FF【招唤坐骑】[召唤栗色马]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤栗色马]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000060', '|cff8000CC【招唤坐骑】[召唤迅捷白马]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤迅捷白马]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000061', '|cff8000FF【招唤坐骑】[召唤暗棕狼]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤暗棕狼]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000062', '|cff8000CC【招唤坐骑】[召唤迅捷森林狼]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤迅捷森林狼]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000063', '|cff8000FF【招唤坐骑】[召唤白山羊]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤白山羊]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000064', '|cff8000CC【招唤坐骑】[召唤迅捷白山羊]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤迅捷白山羊]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000065', '|cff8000FF【招唤坐骑】[召唤条纹夜刃豹]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤条纹夜刃豹]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000066', '|cff8000CC【招唤坐骑】[召唤迅捷霜刃豹]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤迅捷霜刃豹]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000067', '|cff8000FF【招唤坐骑】[召唤蓝色骸骨军马]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤蓝色骸骨军马]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000068', '|cff8000CC【招唤坐骑】[召唤紫色骷髅战马]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤紫色骷髅战马]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000069', '|cff8000FF【招唤坐骑】[召唤灰色科多兽]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤灰色科多兽]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000070', '|cff8000CC【招唤坐骑】[召唤大型白色科多兽]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤大型白色科多兽]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000071', '|cff8000FF【招唤坐骑】[召唤红色机械陆行鸟]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤红色机械陆行鸟]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000072', '|cff8000CC【招唤坐骑】[召唤迅捷白色机械陆行鸟]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤迅捷白色机械陆行鸟]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000073', '|cff8000FF【招唤坐骑】[召唤紫色迅猛龙]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤紫色迅猛龙]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000074', '|cff8000CC【招唤坐骑】[召唤迅捷橙色迅猛龙]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤迅捷橙色迅猛龙]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000075', '|cff8000FF【招唤坐骑】[召唤紫色陆行鸟]', null, null, null, '|cff8000FF【招唤坐骑】[召唤紫色陆行鸟]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000076', '|cff8000CC【招唤坐骑】[召唤迅捷粉色陆行鸟]', null, null, null, '|cff8000CC【招唤坐骑】[召唤迅捷粉色陆行鸟]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000077', '|cff8000FF【招唤坐骑】[召唤紫色雷象]|r', null, null, null, '|cff8000FF【招唤坐骑】[召唤紫色雷象]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000078', '|cff8000CC【招唤坐骑】[召唤重型紫色雷象]|r', null, null, null, '|cff8000CC【招唤坐骑】[召唤重型紫色雷象]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000079', '|cff800099【招唤坐骑】[召唤军用迅猛龙]', null, null, null, '|cff800099【招唤坐骑】[召唤军用迅猛龙]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000080', '|cff800066【招唤坐骑】[召唤驭风者]', null, null, null, '|cff800066【招唤坐骑】[召唤驭风者]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000081', '|cff800044【招唤坐骑】[召唤灵翼幼龙]', null, null, null, '|cff800044【招唤坐骑】[召唤灵翼幼龙]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000082', '|cff800099【招唤坐骑】[召唤黑色军用座虎]|r', null, null, null, '|cff800099【招唤坐骑】[召唤黑色军用座虎]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000083', '|cff800066【招唤坐骑】[召唤狮鹫兽]|r ', null, null, null, '|cff800066【招唤坐骑】[召唤狮鹫兽]|r ', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000084', '|cff800044【招唤坐骑】[召唤虚空鳐]|r ', null, null, null, '|cff800044【招唤坐骑】[召唤虚空鳐]|r ', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000085', '|cff800022【招唤坐骑】[召唤虚空幼龙]|r', null, null, null, '|cff800022【招唤坐骑】[召唤虚空幼龙]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000086', '|cff800022【招唤坐骑】[召唤凤凰]|r', null, null, null, '|cff800022【招唤坐骑】[召唤凤凰]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000087', '|cff800000【在线积分】[查询兑换积分]|r', null, null, null, '|cff800000【在线积分】[查询兑换积分]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000088', '|cff800000【在线工资】[每隔一段时间工资]|r', null, null, null, '|cff800000【在线工资】[每隔一段时间工资]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000089', '|cff800000【修理】[修理你的装备的耐久度]|r', null, null, null, '|cff800000【修理】[修理你的装备的耐久度]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000090', '【银行】[个人各类物品存取]', null, null, null, '【银行】[个人各类物品存取]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000091', '|cff800000【绑定】[记录位置]|r', null, null, null, '|cff800000【绑定】[记录位置]|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000092', '【灵魂医者】[复活]', null, null, null, '【灵魂医者】[复活]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000093', '【部落】[奥格瑞玛]', null, null, null, '【部落】[奥格瑞玛]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000094', '【部落】[雷霆崖]', null, null, null, '【部落】[雷霆崖]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000095', '【部落】[幽暗城]', null, null, null, '【部落】[幽暗城]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000096', '【部落】[银月城]', null, null, null, '【部落】[银月城]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000097', '【联盟】[暴风城]', null, null, null, '【联盟】[暴风城]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000098', '【联盟】[铁炉堡]', null, null, null, '【联盟】[铁炉堡]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000099', '【联盟】[达纳苏斯]', null, null, null, '【联盟】[达纳苏斯]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000100', '【联盟】[埃索达]', null, null, null, '【联盟】[埃索达]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000101', '【中立】[棘齿城]', null, null, null, '【中立】[棘齿城]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000102', '【中立】[藏宝海湾]', null, null, null, '【中立】[藏宝海湾]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000103', '【中立】[冬泉谷]', null, null, null, '【中立】[冬泉谷]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000104', '【中立】[加基森]', null, null, null, '【中立】[加基森]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000105', '【中立】[沙塔斯城]', null, null, null, '【中立】[沙塔斯城]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000106', '【中立】[５２区]', null, null, null, '【中立】[５２区]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000107', '【中立】[奎尔丹纳斯岛]', null, null, null, '【中立】[奎尔丹纳斯岛]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000108', '【外域】[黑暗之门]', null, null, null, '【外域】[黑暗之门]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000109', '【信息】[关于积分商城介绍]', null, null, null, '【信息】[关于积分商城介绍]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000110', '【积分商城】[Ｓ４套装超市]', null, null, null, '【积分商城】[Ｓ４套装超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000111', '【积分商城】[Ｓ２套装超市]', null, null, null, '【积分商城】[Ｓ２套装超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000112', '【积分商城】[Ｓ３套装超市]', null, null, null, '【积分商城】[Ｓ３套装超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000113', '【积分商城】[Ｔ４套装超市]', null, null, null, '【积分商城】[Ｔ４套装超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000114', '【积分商城】[Ｔ５套装超市]', null, null, null, '【积分商城】[Ｔ５套装超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000115', '【积分商城】[Ｔ６套装超市]', null, null, null, '【积分商城】[Ｔ６套装超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000116', '【积分商城】[武器超市]', null, null, null, '【积分商城】[武器超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000117', '【积分商城】[饰品超市]', null, null, null, '【积分商城】[饰品超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000118', '【积分商城】[配方超市]', null, null, null, '【积分商城】[配方超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000119', '【积分商城】[附魔超市]', null, null, null, '【积分商城】[附魔超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000120', '【积分商城】[图样超市]', null, null, null, '【积分商城】[图样超市]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000131', '|cff8000ff<<<上一页>>>|r', null, null, null, '|cff8000ff<<<上一页>>>|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000121', '【消费】[三千积分增加采矿技能十点]', null, null, null, '【消费】[三千积分增加采矿技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000122', '【消费】[三千积分增加炼金技能十点]', null, null, null, '【消费】[三千积分增加炼金技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000123', '【消费】[三千积分增加锻造技能十点]', null, null, null, '【消费】[三千积分增加锻造技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000124', '【消费】[三千积分增加裁缝技能十点]', null, null, null, '【消费】[三千积分增加裁缝技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000125', '【消费】[三千积分增加烹饪技能十点]', null, null, null, '【消费】[三千积分增加烹饪技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000126', '【消费】[三千积分增加制皮技能十点]', null, null, null, '【消费】[三千积分增加制皮技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000127', '【消费】[三千积分增加钓鱼技能十点]', null, null, null, '【消费】[三千积分增加钓鱼技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000128', '【消费】[三千积分增加附魔技能十点]', null, null, null, '【消费】[三千积分增加附魔技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000129', '【消费】[三千积分增加珠宝技能十点]', null, null, null, '【消费】[三千积分增加珠宝技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000130', '【消费】[三千积分增加工程技能十点]', null, null, null, '【消费】[三千积分增加工程技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000132', '【消费】[三千积分增加急救技能十点]', null, null, null, '【消费】[三千积分增加急救技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000133', '【消费】[三千积分增加草药技能十点]', null, null, null, '【消费】[三千积分增加草药技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000134', '【消费】[三千积分增加剥皮技能十点]', null, null, null, '【消费】[三千积分增加剥皮技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000135', '【消费】[三千积分增加开锁技能十点]', null, null, null, '【消费】[三千积分增加开锁技能十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000136', '【消费】[三千积分增加防御武器十点]', null, null, null, '【消费】[三千积分增加防御武器十点]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000137', '|cff8020BB宝石商场中只需要有足够积分即可购买物品。需要的积分由价格来换算，一铜币为一积分，一银币为一百积分，一金币为一万积分。此处物品一但售出概不退货。祝你购物愉快:)|r', null, null, null, '|cff8020BB宝石商场中只需要有足够积分即可购买物品。需要的积分由价格来换算，一铜币为一积分，一银币为一百积分，一金币为一万积分。此处物品一但售出概不退货。祝你购物愉快:)|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000138', '|cff7000ff领取在线工资成功（六十级后请到主城传送师处领取）. |r', null, null, null, '|cff7000ff领取在线工资成功（六十级后请到主城传送师处领取）. |r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000139', '|cffff0000领取工资时间间隔太短. |r', null, null, null, '|cffff0000领取工资时间间隔太短. |r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000140', '|cffff0000你不能在这里召唤坐骑.|r', null, null, null, '|cffff0000你不能在这里召唤坐骑.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000141', '|cffff0000此坐骑需要等级十级才能使用.|r', null, null, null, '|cffff0000此坐骑需要等级十级才能使用.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000142', '|cffff0000此坐骑需要等级二十级才能使用.|r', null, null, null, '|cffff0000此坐骑需要等级二十级才能使用.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000143', '|cffff0000此坐骑需要等级三十级才能使用.|r', null, null, null, '|cffff0000此坐骑需要等级三十级才能使用.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000144', '|cffff0000此坐骑需要等级五十级才能使用.|r', null, null, null, '|cffff0000此坐骑需要等级五十级才能使用.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000145', '|cffff0000此坐骑需要等级六十级才能使用.|r', null, null, null, '|cffff0000此坐骑需要等级六十级才能使用.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000146', '|cffff0000此坐骑需要等级七十级才能使用.|r', null, null, null, '|cffff0000此坐骑需要等级七十级才能使用.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000147', '|cffff0000无法在当前状态下使用宝石.|r', null, null, null, '|cffff0000无法在当前状态下使用宝石.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000148', '|cff2040CC已经临时开通所有飞行点.|r', null, null, null, '|cff2040CC已经临时开通所有飞行点.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000149', '|cff7000ff领取了工资：%d金币.|r', null, null, null, '|cff7000ff领取了工资：%d金币.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000150', '|cffff0000你没开玩笑吧，你的宠物呢?|r', null, null, null, '|cffff0000你没开玩笑吧，你的宠物呢?|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000151', '|cffff0000你的宠物太害羞，跑得太远了.|r', null, null, null, '|cffff0000你的宠物太害羞，跑得太远了.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000152', '|cffff0000目前此项服务只对猎人开放.|r', null, null, null, '|cffff0000目前此项服务只对猎人开放.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000153', '|cffff0000无法在战斗中访问，请停止战斗再访问.|r', null, null, null, '|cffff0000无法在战斗中访问，请停止战斗再访问.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000154', '【城市】[主要城市传送费用十银]', null, null, null, '【城市】[主要城市传送费用十银]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000155', '【初级】[初级副本传送费用一金]', null, null, null, '【初级】[初级副本传送费用一金]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000157', '【中级】[中级副本传送费用二金]', null, null, null, '【中级】[中级副本传送费用二金]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000158', '【高级】[高级副本传送费用三金]', null, null, null, '【高级】[高级副本传送费用三金]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000159', '【外域】[外域副本传送费用五金]', null, null, null, '【外域】[外域副本传送费用五金]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000160', '【诺森德】[传送诺森德费用五金]', null, null, null, '【诺森德】[传送诺森德费用五金]', '【北裂境】[传送北裂境费用五金]', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000161', '【激活】[激活所有飞行点十金]', null, null, null, '【激活】[激活所有飞行点十金]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000162', '【信息】[关于WUZHU 魔兽世界]', null, null, null, '【信息】[关于WUZHU 魔兽世界]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000163', '|cff8020BB欢迎来WUZHU魔兽,感谢暴雪提供这么优秀的游戏，感谢Mangos,ScriptDev2,UDB等开发团队，也感谢你来本魔兽玩,我将在以后时间将本魔兽做得更加完善。我希望您在玩得开心的同时注意游戏时间:)|r', null, null, null, '|cff8020BB欢迎来WUZHU魔兽,感谢暴雪提供这么优秀的游戏，感谢Mangos,ScriptDev2,UDB等开发团队，也感谢你来本魔兽玩,我将在以后时间将本魔兽做得更加完善。我希望您在玩得开心的同时注意游戏时间:)|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000165', '怒焰裂谷[13+]', null, null, null, '怒焰裂谷[13+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000164', '|cff8000ff<<<下一页>>>|r', null, null, null, '|cff8000ff<<<下一页>>>|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000166', '死亡矿井[15+]', null, null, null, '死亡矿井[15+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000167', '哀嚎洞穴[15+]', null, null, null, '哀嚎洞穴[15+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000168', '影牙城堡[22+]', null, null, null, '影牙城堡[22+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000169', '黑暗深渊[24+]', null, null, null, '黑暗深渊[24+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000170', '暴风城监狱[24+]', null, null, null, '暴风城监狱[24+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000171', '剃刀沼泽[29+]', null, null, null, '剃刀沼泽[29+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000172', '诺莫瑞根[29+]', null, null, null, '诺莫瑞根[29+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000173', '血色修道院[34+]', null, null, null, '血色修道院[34+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000174', '剃刀高地[37+]', null, null, null, '剃刀高地[37+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000175', '奥达曼[35+]', null, null, null, '奥达曼[35+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000176', '祖尔法拉克[44+]', null, null, null, '祖尔法拉克[44+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000177', '玛拉顿[46+]', null, null, null, '玛拉顿[46+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000178', '失落的神庙[45+]', null, null, null, '失落的神庙[45+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000179', '黑石深渊[52+]', null, null, null, '黑石深渊[52+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000180', '通灵学院[57+]', null, null, null, '通灵学院[57+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000181', '厄运之槌(北区)[55+]', null, null, null, '厄运之槌(北区)[55+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000182', '厄运之槌(东区)[55+]', null, null, null, '厄运之槌(东区)[55+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000183', '厄运之槌(西区)[55+]', null, null, null, '厄运之槌(西区)[55+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000184', '斯坦索姆[58+]', null, null, null, '斯坦索姆[58+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000185', '黑石塔[55+]', null, null, null, '黑石塔[55+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000186', '溶火之心[60团]', null, null, null, '溶火之心[60团]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000187', '黑石塔上[60团]', null, null, null, '黑石塔上[60团]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000188', '祖尔格拉布[60团]', null, null, null, '祖尔格拉布[60团]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000189', '黑翼之巢[60团]', null, null, null, '黑翼之巢[60团]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000190', '安其拉[60团]', null, null, null, '安其拉[60团]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000191', '安其拉废墟[60团]', null, null, null, '安其拉废墟[60团]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000192', '奥妮克希亚的巢穴[60团]', null, null, null, '奥妮克希亚的巢穴[60团]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000193', '地狱火城墙[60+]', null, null, null, '地狱火城墙[60+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000194', '鲜血熔炉[61+]', null, null, null, '鲜血熔炉[61+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000195', '奴隶围栏[62+]', null, null, null, '奴隶围栏[62+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000196', '幽暗沼泽[63+]', null, null, null, '幽暗沼泽[63+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000197', '法力陵墓[64+]', null, null, null, '法力陵墓[64+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000198', '奥金尼地穴[65+]', null, null, null, '奥金尼地穴[65+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000199', '敦霍尔德[66+]', null, null, null, '敦霍尔德[66+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000200', '塞泰克大厅[67+]', null, null, null, '塞泰克大厅[67+]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000201', '暮色森林[野外]', null, null, null, '暮色森林[野外]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000202', '辛特兰　[野外]', null, null, null, '辛特兰　[野外]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000203', '灰　谷　[野外]', null, null, null, '灰　谷　[野外]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000204', '艾萨拉　[野外]', null, null, null, '艾萨拉　[野外]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000205', '菲拉斯　[野外]', null, null, null, '菲拉斯　[野外]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000206', '诅咒之地[野外]', null, null, null, '诅咒之地[野外]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000207', '水晶谷　[野外]', null, null, null, '水晶谷　[野外]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000208', '【灰熊丘陵】', null, null, null, '【灰熊丘陵】', '【灰白之丘】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000209', '【北风苔原】', null, null, null, '【北风苔原】', '【北風凍原】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000210', '【龙骨荒野】', null, null, null, '【龙骨荒野】', '【龍骨荒野】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000211', '【嚎风峡湾】', null, null, null, '【嚎风峡湾】', '【凜風峽灣】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000212', '【祖  达  克】', null, null, null, '【祖  达  克】', '【祖爾德拉克】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000213', '【风暴峭壁】', null, null, null, '【风暴峭壁】', '【風暴群山】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000214', '【冰冠冰川】', null, null, null, '【冰冠冰川】', '【寒冰皇冠】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000215', '【索拉查盆地】', null, null, null, '【索拉查盆地】', '【休拉薩盆地】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000216', '【冬拥湖】', null, null, null, '【冬拥湖】', '【冬握湖】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000217', '【晶歌森林】', null, null, null, '【晶歌森林】', '【水晶之歌森林】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000218', '【奥核之心[副本]】', null, null, null, '【奥核之心[副本]】', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000219', '【抚育之渊[副本]】', null, null, null, '【抚育之渊[副本]】', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000220', '【黑色领区[副本]】', null, null, null, '【黑色领区[副本]】', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000221', '破碎大厅[70]', null, null, null, '破碎大厅[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000222', '蒸汽洞窟[70]', null, null, null, '蒸汽洞窟[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000223', '暗影迷宫[70]', null, null, null, '暗影迷宫[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000224', '能源舰[70]', null, null, null, '能源舰[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000225', '生态船[70]', null, null, null, '生态船[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000226', '黑色沼泽[70]', null, null, null, '黑色沼泽[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000227', '禁魔监狱[70]', null, null, null, '禁魔监狱[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000228', '魔导师平台[70]', null, null, null, '魔导师平台[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000229', '卡拉赞[70]', null, null, null, '卡拉赞[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000230', '|cff2040CC已经开通所有飞行点，花费：%d金币.|r', null, null, null, '|cff2040CC已经开通所有飞行点，花费：%d金币.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000231', '格鲁尔的巢穴[70]', null, null, null, '格鲁尔的巢穴[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000232', '玛瑟里顿的巢穴[70]', null, null, null, '玛瑟里顿的巢穴[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000233', '风暴要塞[70]', null, null, null, '风暴要塞[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000234', '毒蛇神殿[70]', null, null, null, '毒蛇神殿[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000235', '祖阿曼[70]', null, null, null, '祖阿曼[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000236', '海加尔山[70]', null, null, null, '海加尔山[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000237', '太阳之井[70]', null, null, null, '太阳之井[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000238', '黑暗神庙[70]', null, null, null, '黑暗神庙[70]', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000239', '|cff7000ff领取了工资：%d金币.|r', null, null, null, '|cff7000ff领取了工资：%d金币.|r', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000240', '世界未端小洒馆', null, null, null, '世界未端小洒馆', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000241', '占星者银行', null, null, null, '占星者银行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000242', '奥尔多银行', null, null, null, '奥尔多银行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000243', '占星者旅店', null, null, null, '占星者旅店', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000244', '奥尔多旅店', null, null, null, '奥尔多旅店', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000245', '占星者兽栏管理员', null, null, null, '占星者兽栏管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000246', '奥尔多兽栏管理员', null, null, null, '奥尔多兽栏管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000247', '奥特兰克山谷战场军官', null, null, null, '奥特兰克山谷战场军官', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000248', '种族和主战场军官', null, null, null, '种族和主战场军官', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000249', '竞技场军官', null, null, null, '竞技场军官', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000250', '魔法织布机', null, null, null, '魔法织布机', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000251', '炼金实验室', null, null, null, '炼金实验室', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000252', '宝石商人', null, null, null, '宝石商人', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000253', '占星者宝石商人', null, null, null, '占星者宝石商人', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000254', '奥尔多宝石商人', null, null, null, '奥尔多宝石商人', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000255', 'Western拍卖行', null, null, null, 'Western拍卖行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000256', 'Royal Exchange拍卖行', null, null, null, 'Royal Exchange拍卖行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000257', '银月城旅店', null, null, null, '银月城旅店', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000258', 'Wayfarer\'s Rest tavern', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000259', '我想看看你的商品.', null, null, null, '我想看看你的商品.', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000260', '训练我!', null, null, null, '训练我!', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000261', '银行', null, null, null, '银行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000262', '铁炉堡银行', null, null, null, '铁炉堡银行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000263', '暴风城银行', null, null, null, '暴风城银行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000264', '双足飞龙管理员', null, null, null, '双足飞龙管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000265', '狮鹫管理员', null, null, null, '狮鹫管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000266', '蝙蝠管理员', null, null, null, '蝙蝠管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000267', '角鹰兽管理员', null, null, null, '角鹰兽管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000268', '飞艇管理员', null, null, null, '飞艇管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000269', '地铁', null, null, null, '地铁', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000270', '鲁瑟兰村码头', null, null, null, '鲁瑟兰村码头', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000271', '飞行管理员', null, null, null, '飞行管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000272', '拍卖行', null, null, null, '拍卖行', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000273', '公会注册管理员', null, null, null, '公会注册管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000274', '旅店', null, null, null, '旅店', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000275', '邮箱', null, null, null, '邮箱', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000276', '宠物管理员', null, null, null, '宠物管理员', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000277', '武器大师', null, null, null, '武器大师', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000278', '军官休息室', null, null, null, '军官休息室', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000279', '战场军官', null, null, null, '战场军官', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000280', '理发师', null, null, null, '理发师', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000281', '种族训练师', null, null, null, '种族训练师', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000282', '职业训练师', null, null, null, '职业训练师', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000283', '魔法力量宝典', null, null, null, '魔法力量宝典', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000284', '奥特兰克山谷', null, null, null, '奥特兰克山谷', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000285', '阿拉希盆地', null, null, null, '阿拉希盆地', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000286', '战歌峡谷', null, null, null, '战歌峡谷', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000287', '竞技场', null, null, null, '竞技场', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000288', '风暴之眼', null, null, null, '风暴之眼', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000289', '远祖滩头', null, null, null, '远祖滩头', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000290', '死亡骑士', null, null, null, '死亡骑士', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000291', '德鲁伊', null, null, null, '德鲁伊', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000292', '猎人', null, null, null, '猎人', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000293', '牧师', null, null, null, '牧师', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000294', '盗贼', null, null, null, '盗贼', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000295', '战士', null, null, null, '战士', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000296', '圣骑士', null, null, null, '圣骑士', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000297', '萨满祭司', null, null, null, '萨满祭司', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000298', '法师', null, null, null, '法师', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000299', '术土', null, null, null, '术土', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000301', '炼金术', null, null, null, '炼金术', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000302', '锻造', null, null, null, '锻造', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000303', '烹饪', null, null, null, '烹饪', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000304', '附魔', null, null, null, '附魔', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000305', '工程学', null, null, null, '工程学', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000306', '急救', null, null, null, '急救', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000307', '草药学', null, null, null, '草药学', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000308', '制皮', null, null, null, '制皮', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000309', '裁缝', null, null, null, '裁缝', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000310', '采矿', null, null, null, '采矿', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000311', '钓鱼', null, null, null, '钓鱼', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000312', '剥皮', null, null, null, '剥皮', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000313', '珠宝加工', null, null, null, '珠宝加工', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000314', '铭文', null, null, null, '铭文', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000315', '此物品已经被限制售出，如有疑问请咨询WUZHU,QQ:85267512', null, null, null, '此物品已经被限制售出，如有疑问请咨询WUZHU,QQ:85267512', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000316', '你的积分不够，此物品需要%u点积分。', null, null, null, '你的积分不够，此物品需要%u积分。', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000317', '您增加%u点积分，当前共有%u点积分。', null, null, null, '您增加%u点积分，当前共有%u点积分。', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000318', '您消费%u点积分，现在还有%u点积分。', null, null, null, '您消费%u点积分，现在还有%u点积分。', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000319', '您的角色如果卡死，请输入 /g .start', null, null, null, '您的角色如果卡死，请输入 /g .start', null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000320', '【部落】[北風凍原：戰歌堡]', null, null, null, null, '【部落】[北風凍原：戰歌堡]', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000321', '【部落】[凜風峽灣：復仇臺地]', null, null, null, null, '【部落】[凜風峽灣：復仇臺地]', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000322', '【联盟】[北風凍原：驍勇要塞]', null, null, null, null, '【聯盟】[北風凍原：驍勇要塞]', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000323', '【联盟】[凜風峽灣：瓦爾加德]', null, null, null, null, '【聯盟】[凜風峽灣：瓦爾加德]', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000324', '【中立】达拉然', null, null, null, '【中立】达拉然', '【中立】达拉然', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000325', '【重置副本】[2000积分重置团队副本]', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000326', '重置副本数:%d。', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000327', '您没有保存的副本进度。', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000328', '|cff6000ff【传送】[临时传送点]|r', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000329', '|cff6000ff【副本】[納克薩瑪斯][BOSS设置不会狂暴]|r', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000330', '|cff6000ff<<退出>>|r', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000331', '|cff6000ff【副本】[阿尔卡冯的宝库][不能积分重置]|r', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000332', '【攻城區】', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000333', '【前厅】', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000334', '【巧思回廊】', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000335', '【创思之厅】', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000336', '【癫狂斜廊】', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000337', '【未记录】', null, null, null, '【未记录】', '【未记录】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000338', '【记录】', null, null, null, '【记录】', '【记录】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000339', '【传送】', null, null, null, '【传送】', '【传送】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000340', '【删除】', null, null, null, '【删除】', '【删除】', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000341', '记录成功!', null, null, null, '绑定成功!', '绑定成功!', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000342', '删除成功!', null, null, null, '删除成功!', '删除成功!', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000343', '本记录没有记录信息!', null, null, null, '本记录没有记录信息!', '本记录没有记录信息!', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000344', '您无法在副本中记录位置!', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000345', '【银行】[公会各类物品存取]', null, null, null, null, null, null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000346', '位置查看', null, null, null, '位置查看', '位置查看', null, null, null, null);
INSERT INTO `wuzhu_texts` VALUES ('-6000347', '你要查看的位置不在本地图!', null, null, null, '你要查看的位置不在本地图!', '你要查看的位置不在本地图!', null, null, null, null);
